name: "Display info"
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:
  v1:
    runs-on: linux
    steps:
      - run: echo "Deploying new version ${{ github.event.inputs.version }}"
