name: "Déploiement stambia"
on:
  workflow_dispatch:
    inputs:
      sVersion:
        description: 'Version'
        required: true
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'dev'
        options:
          - 'dev'
          - 'pre-production'
          - 'production'
jobs:
  start-up:
    runs-on: linux
    steps:
      - run: echo "Start-up"
      - uses: ../actions/main/print-info-version@v1
        with:
          version: ${{ github.event.inputs.sVersion }}
  print-info-version:
    needs: start-up
    runs-on: linux
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Read file content
        id: version
        run: |
          content=`cat ./version.txt`
          echo "::set-output name=versionInfo::${content:1}"
      - name: Print file content
        run: echo "Deploying new version ${{ steps.version.outputs.versionInfo }}/${{ github.event.inputs.sVersion }} on ${{ github.event.inputs.environment }} in ${{ github.event.inputs.logLevel }}"
  clean-up:
    needs: print-info-version
    runs-on: linux
    steps:
      - run: echo "clean-up"
