on:
  create:
    tags:
      - 'p*'
jobs:
  print-info-version:
    runs-on: linux
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Read file content
        id: version
        run: |
          content=`cat ./version.txt`
          echo "::set-output name=versionInfo::${content:1}"
      - name: Print file content
        run: echo "Deploying new version ${{ steps.version.outputs.versionInfo }}"
