on:
  push:
    paths:
      - 'version.txt'
jobs:
  print-info-version:
    runs-on: linux
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Read file content
        id: version
        run: 'cat ./version.txt'
      - name: Print file content
        run: echo "Deploying new version ${{ steps.version.outputs.content }}"
