on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'dev'
        options:
          - 'dev'
          - 'pre-production'
          - 'production'
jobs:
  print-info-version:
    runs-on: linux
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Read file content
        id: version
        run: |
          content=`cat ./version.txt`
          echo "::set-output name=versionInfo::${content:1}"
      - name: Print file content
        run: echo "Deploying new version ${{ steps.version.outputs.versionInfo }} on ${{ github.event.inputs.environment }} in ${{ github.event.inputs.logLevel }}"